exclude: ".*/data/.*|.maint/.*_author.*.py|.vscode/.*.json"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.svg'
      - id: end-of-file-fixer
        exclude: '.*\.svg'
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
    hooks:
      - id: rst-backticks
        exclude: ^CHANGES.rst
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # frozen: v0.15.12
    hooks:
      - id: ruff-check
        args: [ --fix, --show-fixes ]
      - id: ruff-format
ci:
  autoupdate_schedule: monthly
