version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      - git fetch --unshallow

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
