# vim ft=yaml
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.6

# disable the default submodule logic
git:
  submodules: false

before_install:
  - python -m pip install --upgrade pip
  - pip install "flake8<3.0" flake8-putty

script:
  - flake8 fmriprep wrapper
