version: 2
jobs:

  build_images:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: /home/circleci/fmriprep
    steps:
      - restore_cache:
          keys:
            - docker-v1-{{ .Branch }}-{{ epoch }}
            - docker-v1-{{ .Branch }}-
            - docker-v1-
          paths:
            - /tmp/cache/docker.tar.gz
            - /tmp/cache/ubuntu.tar.gz
      - checkout:
          path: /home/circleci/fmriprep
      - run:
          name: Update fMRIPrep version
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              sed -i -E "s/(__version__ = )'[A-Za-z0-9.-]+'/\1'${CIRCLE_TAG}'/" fmriprep/info.py
              sed -i -E "s/(__version__ = )'[A-Za-z0-9.-]+'/\1'${CIRCLE_TAG}'/" wrapper/fmriprep_docker.py
              sed -i -E "s/(var version = )'[A-Za-z0-9.-]+'/\1'${CIRCLE_TAG}'/" docs/citing.rst
            fi
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            docker info
            set +o pipefail
            docker load -i /tmp/cache/ubuntu.tar.gz | true
            docker load -i /tmp/cache/docker.tar.gz | true
            docker images
      # - run:
      #     name: Pull ubuntu:xenial-20161213
      #     no_output_timeout: 60m
      #     command: docker pull ubuntu:xenial-20161213 || true

      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=poldracklab/fmriprep \
                --rm=false \
                -t poldracklab/fmriprep:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION=${CIRCLE_TAG:-latest} . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]

      - run:
          name: Docker save
          no_output_timeout: 20m
          command: |
            mkdir -p /tmp/cache
            docker save ubuntu:xenial-20161213 | gzip -1 > /tmp/cache/ubuntu.tar.gz
            docker save poldracklab/fmriprep:latest \
            | gzip -1 > /tmp/cache/docker.tar.gz

      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/ubuntu.tar.gz
            - cache/docker.tar.gz

  get_data:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - restore_cache:
          keys:
            - data-v1-{{ .Branch }}-{{ epoch }}
            - data-v1-{{ .Branch }}-
            - data-v1-
      - run:
          name: Get test data from ds000005
          command: |
            mkdir -p /tmp/data
            if [[ ! -d /tmp/data/ds005 ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ds005_downsampled.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/57f32a429ad5a101f977eb75"
              tar xzf ds005_downsampled.tar.gz -C /tmp/data/
            fi
      - run:
          name: Get test data from ds000054
          command: |
            if [[ ! -d /tmp/data/ds054 ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ds054_downsampled.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/57f32c22594d9001ef91bf9e"
              tar xzf ds054_downsampled.tar.gz -C /tmp/data/
            fi
      - run:
          name: Get FreeSurfer derivatives for ds000005
          command: |
            if [[ ! -d /tmp/data/freesurfer ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ds005_derivatives_freesurfer.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/58fe59eb594d900250960180"
              tar xzf ds005_derivatives_freesurfer.tar.gz -C /tmp/data/
            fi
      - run:
          name: Store FreeSurfer license file
          command: |
            mkdir -p /tmp/data/fslicense
            cd /tmp/data/fslicense
            echo "cHJpbnRmICJrcnp5c3p0b2YuZ29yZ29sZXdza2lAZ21haWwuY29tXG41MTcyXG4gKkN2dW12RVYzelRmZ1xuRlM1Si8yYzFhZ2c0RVxuIiA+IGxpY2Vuc2UudHh0Cg==" | base64 -d | sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - data/*
      - save_cache:
         key: data-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/data/*

  update_cache:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/fmriprep
    steps:
      - attach_workspace:
          at: /tmp
      - save_cache:
         key: docker-v1-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/cache/docker.tar.gz
            - /tmp/cache/ubuntu.tar.gz

  test_pytest:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/fmriprep
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load saved Docker images.
          no_output_timeout: 60m
          command: |
            set +o pipefail
            docker load -i /tmp/cache/ubuntu.tar.gz | true
            docker load -i /tmp/cache/docker.tar.gz | true
            docker images
      - run:
          name: Run fMRIPrep tests
          no_output_timeout: 2h
          command: |
            docker run -ti --rm=false \
              --entrypoint="/usr/local/miniconda/bin/py.test" \
              poldracklab/fmriprep:latest . \
              --doctest-modules --ignore=docs --ignore=setup.py
      - checkout
      - run:
          name: Test fmriprep-wrapper
          command: |
            pip install future numpy
            pip install --upgrade wrapper/
            fmriprep-docker -i poldracklab/fmriprep:latest --help
      - store_artifacts:
          path: /home/circleci/out/tests


  build_docs:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/out/docs
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load saved Docker images.
          no_output_timeout: 60m
          command: |
            set +o pipefail
            docker load -i /tmp/cache/ubuntu.tar.gz | true
            docker load -i /tmp/cache/docker.tar.gz | true
            docker images
      - run:
          name: Build fMRIPrep documentation
          no_output_timeout: 2h
          command: |
            docker run -ti --rm=false -v $PWD:/_build_html \
              --entrypoint=sphinx-build poldracklab/fmriprep:latest \
              -T -E -b html -d _build/doctrees-readthedocs -W -D \
              language=en docs/ /_build_html 2>&1 \
              | tee $PWD/builddocs.log
            cat $PWD/builddocs.log
            grep -qv "ERROR" $PWD/builddocs.log
      - store_artifacts:
          path: /home/circleci/out/docs

  ds005:
    machine:
      image: circleci/classic:201711-01
    working_directory: /home/circleci/ds005
    - checkout:
      path: /home/circleci/fmriprep
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Setting up test
          command: |
            mkdir -p /home/circleci/ds005/derivatives
            cp -al /tmp/data/freesurfer /home/circleci/ds005/derivatives/freesurfer
            printf "[execution]\nstop_on_first_crash = true\nremove_unnecessary_outputs = false" > nipype.cfg
            cd /home/circleci/fmriprep
            pip install future numpy
            pip install --upgrade wrapper/
      - run:
          name: Load saved Docker images.
          no_output_timeout: 60m
          command: |
            set +o pipefail
            docker load -i /tmp/cache/ubuntu.tar.gz | true
            docker load -i /tmp/cache/docker.tar.gz | true
            docker images
      - run:
          name: Build fMRIPrep documentation
          no_output_timeout: 2h
          command: |
            fmriprep-docker -i poldracklab/fmriprep:latest \
                --config $HOME/nipype.cfg -w work /tmp/data/ds005 $PWD/derivatives participant --debug --write-graph --use-syn-sdc --use-aroma --ignore-aroma-denoising-errors --mem_mb 4096 --nthreads 2 --anat-only
      - store_artifacts:
          path: /home/circleci/ds005/derivatives
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - get_data
      - build_images
      - update_cache:
          requires:
            - build_images
      - test_pytest:
          requires:
            - build_images
      - build_docs:
          requires:
            - build_images
      - ds005:
          requires:
            - get_data
            - build_images