name: Contribution checks

on:
  push:
    branches:
      - master
      - maint/*
  pull_request:
    branches:
      - master
      - maint/*

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check fMRIPrep
        run: |
          pipx run ruff fmriprep
          pipx run ruff format --diff fmriprep
      - name: Check wrapper
        run: |
          pipx run ruff wrapper
          pipx run ruff format --diff wrapper
          python -m ruff check --diff --check wrapper
          python -m ruff format --diff --check wrapper
  
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
