name: Prerelease tests

on:
  push:
    branches:
      - ci/prerelease
  schedule:
    - cron: '0 0 * * 1'
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Force tox and pytest to use color
env:
  FORCE_COLOR: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    # Check each OS, all supported Python, minimum versions and latest releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.12', '3.13', '3.14']

    env:
      DEPENDS: pre

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/templateflow
          key: templateflow-v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends graphviz
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install tox
        run: |
          uv tool install --with=tox-uv --with=tox-gh-actions tox
      - name: Show tox config
        run: tox c
      - name: Setup test suite
        run: tox run -vv --notest
      - name: Run test suite
        id: pre
        run: tox -v --skip-pkg-install --exit-and-dump-after 1200
      - name: Minimize uv cache
        run: uv cache prune --ci
        if: ${{ always() }}
      - name: Create issue
        # Workflows triggered by schedule only notify the workflow creator
        # So let's open an issue to make sure this is visible to all
        if: ${{ steps.pre.outcome != 'success' }}
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          workflow_name: PRE-RELEASE TESTS
        with:
          filename: .github/workflow_failure.md
          update_existing: true
          search_existing: open
      - name: Return failure
        if: ${{ steps.pre.outcome != 'success' }}
        run: exit 1
